<? php

$destinations = array("Datça", "Shikaoi", "Santiago de Cuba", "Calgary", "Tromsø", "Limerick", "Nuuk", "Chihuahua", "Limón", "Val Paraíso", "Cape Town", "Gibraltar", "Algiers", "Kuala Lumpur", "Fluk", "Darwin", "Isle of Man", "Rønne", "St. Petersborg", "Pyongnyang", "Sichuan", "Xigazê", "Goa", "Riyadh", "Dar es Salaam", "Bata", "Mu Ko Similan", "Haifa", "Chania", "Prag", "Marseille", "Amsterdam");
 $rand_keys = array_rand($destinations, 50);
  echo $input[$rand_keys[0]] . "\n";
  echo $input[$rand_keys[1]] . "\n";
echo $input[$rand_keys[2]] . "\n";
echo $input[$rand_keys[3]] . "\n";
echo $input[$rand_keys[4]] . "\n";
echo $input[$rand_keys[5]] . "\n";
echo $input[$rand_keys[6]] . "\n";
echo $input[$rand_keys[7]] . "\n";
echo $input[$rand_keys[8]] . "\n";
echo $input[$rand_keys[9]] . "\n";
echo $input[$rand_keys[10]] . "\n";
echo $input[$rand_keys[11]] . "\n";
echo $input[$rand_keys[12]] . "\n";
echo $input[$rand_keys[13]] . "\n";
echo $input[$rand_keys[14]] . "\n";
echo $input[$rand_keys[15]] . "\n";
echo $input[$rand_keys[16]] . "\n";
echo $input[$rand_keys[17]] . "\n";
echo $input[$rand_keys[18]] . "\n";
echo $input[$rand_keys[19]] . "\n";
echo $input[$rand_keys[20]] . "\n";
echo $input[$rand_keys[21]] . "\n";
echo $input[$rand_keys[22]] . "\n";
echo $input[$rand_keys[23]] . "\n";
echo $input[$rand_keys[24]] . "\n";
echo $input[$rand_keys[25]] . "\n";
echo $input[$rand_keys[26]] . "\n";
echo $input[$rand_keys[27]] . "\n";
echo $input[$rand_keys[28]] . "\n";
echo $input[$rand_keys[29]] . "\n";
echo $input[$rand_keys[30]] . "\n";
echo $input[$rand_keys[31]] . "\n";
echo $input[$rand_keys[32]] . "\n";
echo $input[$rand_keys[33]] . "\n";
echo $input[$rand_keys[34]] . "\n";
echo $input[$rand_keys[35]] . "\n";
echo $input[$rand_keys[36]] . "\n";
echo $input[$rand_keys[37]] . "\n";
echo $input[$rand_keys[38]] . "\n";
echo $input[$rand_keys[39]] . "\n";
echo $input[$rand_keys[40]] . "\n";
echo $input[$rand_keys[41]] . "\n";
echo $input[$rand_keys[42]] . "\n";
echo $input[$rand_keys[43]] . "\n";
echo $input[$rand_keys[44]] . "\n";
echo $input[$rand_keys[45]] . "\n";
echo $input[$rand_keys[46]] . "\n";
echo $input[$rand_keys[47]] . "\n";
echo $input[$rand_keys[48]] . "\n";
echo $input[$rand_keys[49]] . "\n";
echo $input[$rand_keys[50]] . "\n";

?>